### ISSUE TITLE
Can it also wake the device?

### ISSUE THREAD

**Issue by Jazz747** [MrToph/react-native-app-launcher#1]
The module works very good with launching the app, but when the screen is off, it doesn't wake the device. How can this be achieved here?

I am doing an alarm clock similair like your motivational app which wakes the device. I've been looking all over the source code for the thing that wakes it but to no avail. :(

**Comment by MrToph** [comment]
I'm using this in my motivation app and it works.
So, if you checked most of the source code already, it 's probably because you're missing some configuration?

Check out this [AndroidManifest](https://github.com/MrToph/react-native-motivation-app/blob/master/android/app/src/main/AndroidManifest.xml), especially:

`
 <uses-permission android:name="android.permission.WAKE_LOCK"/>
`

These flags are also important in [MainActivity.java](https://github.com/MrToph/react-native-motivation-app/blob/master/android/app/src/main/java/io/cmichel/motivation/MainActivity.java)

```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final Window win = getWindow();
        win.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED |
                WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD |
                WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON |
                WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON |
                WindowManager.LayoutParams.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON);
    }
```

These should be all the configurations I did with regards to waking up from locked screen. Tell me if it works :)

**Comment by Jazz747** [comment]
Yes! I've put the permission in the Manifest but I was missing the flags and the corresponding imports of `Window`, `Windowmanager` and `Bundle`. Now it wakes the device. Thank you for your quick response, cheers :)
